---
title: "Cytokine_HSP60_Analysis"
author: "Usman"
date: "2024-06-23"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE )
library(readxl)
library(janitor)
library(tidyverse)

library(dplyr)
library(MASS)
library(factoextra)
library(rstatix)
library(ggpubr)
Chlamydia_Venn <- read_excel("C:/Users/Usman Ola/Downloads/Chlamydia Trichomatis.xlsx")
Chlamydia_logistic_reg <- clean_names(Chlamydia_Venn)
names(Chlamydia_logistic_reg) # All variables names are automagically cleaned!
newdata<-Chlamydia_logistic_reg[!Chlamydia_logistic_reg$how_long_7=="Nil",]%>%
  mutate(age_cat=cut(age,
                     breaks = c(0,35,Inf),
                     labels = c("<35",">35")),
         Marital_dur=ifelse(how_long_7=="1","First_Child","Children"),
         Marital_cat=cut(as.numeric(how_long_7),
                         c(0,20,Inf),
                         c("≤20",">20")),
         Times_mar=case_when(how_times=="Fouth"~"second",
                             how_times=="Third"~"second",
                             how_times=="First"~"first",
                             how_times=="Second"~"second"),
         wom_edu=str_replace(level_edu,"p","P"),
         husband_occ=case_when(
           husb_occ=="Leccturer"~"Lecturer",
           husb_occ=="Teacher"~"Lecturer",
           husb_occ=="Civil Serv"~"Civil_ser",
           husb_occ=="Lecturer"~"Lecturer",
           husb_occ=="Civil serv"~"Civil_ser",
           husb_occ=="Publicserv"~"Civil_ser",
           husb_occ=="Civilserv"~"Civil_ser",
           husb_occ=="Bussiness"~"Bussines",
           husb_occ=="Business"~"Bussines",
           husb_occ=="Carpenter"~"Artisan",
           husb_occ=="Artisan"~"Artisan",
           husb_occ=="Farmer"~"Farmer",
           TRUE~"others"),
         fam_type=str_replace_all(family_typ,c("mono"="Mono")),
         woman_occ=case_when(
           occup=="Teacher"~"Teacher",
           occup=="teacher"~"Teacher",
           occup=="Civil Serv"~"Civil_ser",
           occup=="House wife"~"House_wife",
           occup=="Civil serv"~"Civil_ser", 
           occup=="Civilserv"~"Civil_ser",
           occup=="Student"~"Student",
           occup=="Tailor"~"Artisan",
           occup=="Artisan"~"Artisan", 
           occup=="Farmer"~"Farmer",
           TRUE~"others"),woman_occ1=ifelse(woman_occ=="Teacher","Teacher","other"),
         woman_occ2=str_replace_all(woman_occ,c("Farmer"="others","Student"="others","Teacher"="others","Artisan"="others")),
         woman_occ2f=factor(woman_occ2,levels=c("others","House_wife","Civil_ser")),
         any_preg=recode(any_preg,"No"="Primary_infert",
                         "Yes"="secondary_infert"),
         how_many=recode(
           how_many,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=0,
           "Once"=1,
           "One"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3),
         Pregnancy=cut(how_many,c(-Inf,0.9,1,5,10),
                       c("No_preg","once","2-5","6-10")), 
         to_term=recode(
           to_term,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=0,
           "Once"=1,
           "One"=1,"0ne"=1,"one"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3,"Nine"=9),
         term_cat=cut(to_term,c(-Inf,0.9,1,5,10),right=TRUE,
                      c("no_child","One_child","2-5","6-10"),.drop=FALSE) ,
         age_of_last=as.numeric(str_replace(age_of_last,"Nil","0")),
         ageoflast_cat=cut(age_of_last,c(-Inf,0.9,1,5,10,15,20),
                           c("none","One_year","1-5","6-10","11-15","16-20")),
         family_pla,
         which_one,
         how_long_20=recode(
           how_long_20,"1"=1,"2"=2,"3"=3,"5"=5,"6"=6,"Nil"=0 ,"<6M"=1,"NiL"=0),
         Vaginal_discharge=str_replace_all(color,c("NIL"="Nil","Brownish"="Reddish")),
         vaginal_discharge1=str_replace_all(Vaginal_discharge,c("Brownish"="Yellowish","Reddish"="Yellowish")),
         il_10_quatile=ntile(il_10_avrg,3),
         il_10_quatile_cat=recode(il_10_quatile,"1"="firstq","2"="sec","3"="thir"),
         ifn_gam_quatile=ntile(ifn_gamm_avrg,3),
         ifn_gam_quatile_cat=recode(ifn_gam_quatile,"1"="firstq","2"="sec","3"="thir"),
         hsp_60_quatile=ntile(hsp_60_avrg,3),chlamydia_pos=ifelse(ig_g=="Pos"|ig_m=="Pos","Pos","Neg"),
         hsp_60_quatile_cat=recode(hsp_60_quatile,"1"="firstq","2"="sec","3"="thir")
         
  )

```
## Level of Interleukin-10, Interferon-γ, Chlamydial heat shock protein and Th1/Th2 ratio stratified by anti-Ct antibody seroreactivity response in fertile and infertile female attending antenatal and fertility clinic.

```{r}
 pwc <- newdata %>%
  group_by(chlamydia_pos)%>%
  dunn_test(il_10_avrg~group,p.adjust.method = "none")
pwc <- pwc %>% add_xy_position(x="chlamydia_pos")

pwc1 <- newdata %>%
  group_by(group)%>%
  dunn_test(il_10_avrg~chlamydia_pos,p.adjust.method = "none")
pwc1 <- pwc1 %>% add_xy_position(x="chlamydia_pos",group = "group")



Il_10<-ggplot(newdata,aes(x=chlamydia_pos,y=il_10_avrg,col=group))+
  geom_boxplot()+scale_color_manual(name="",values = c("blue","black"))+
  geom_point(position=position_jitterdodge())+
  stat_pvalue_manual(pwc, tip.length = 0.02,hide.ns = FALSE,
  y.position = c(500,620),bracket.size = 1,size=7,
  label = "{format.pval(pv=p.adj,digits = 2)}",color="darkblue")+
  stat_pvalue_manual(pwc1,y.position = c(650,585), 
  tip.length = 0.02,hide.ns = FALSE,bracket.size = 1,size=7, 
    label = "p.adj.signif",color="darkblue")+
 # label = "p={format.pval(pv=p.adj,digits = 2)}",color="darkblue")+
  scale_y_continuous(expand=expansion(mult=c(0.05,0.1)))+theme_minimal()+
  theme(legend.position = "null",
    axis.title=element_text(colour="darkblue",        
    size=15,face = "bold"),axis.title.y=element_text(colour="darkblue"),
    axis.text.x = element_text(size=10,face = "bold"),
    axis.ticks = element_line(size = 0.1),axis.line = element_line(size=1))+
  scale_x_discrete(label=c("Ct-negative","Ct-positive"))+
  labs(y = "Interleukin-10 (pg/mL)",x=expression(bold(Serum~italic(Ct)~"-immoglubulin response")))

 
# Interferon gamma levels in Ct-immunoglobulin Positive or Negative participants
pwc_ifn <- newdata %>%
  group_by(chlamydia_pos)%>%
  dunn_test(ifn_gamm_avrg~group,p.adjust.method = "none")
pwc_ifn <- pwc %>% add_xy_position(x="chlamydia_pos")

pwc_ifn1 <- newdata %>%
  group_by(group)%>%
  dunn_test(ifn_gamm_avrg~chlamydia_pos,p.adjust.method = "none")
pwc_ifn1 <- pwc_ifn1 %>% add_xy_position(x="chlamydia_pos",group = "group")


Ifn_gam<-ggplot(newdata,aes(x=chlamydia_pos,y=ifn_gamm_avrg,col=group))+
  geom_boxplot()+scale_color_manual(name="",values = c("blue","black"))+
  geom_point(position=position_jitterdodge())+
  stat_pvalue_manual(pwc_ifn, tip.length = 0.02,hide.ns = FALSE,
  y.position = c(350,350),bracket.size = 1,size=7,
  label = "p.adj.signif",color="darkblue")+
  stat_pvalue_manual(pwc_ifn1,y.position = c(400,385), tip.length = 0.02,
  hide.ns = FALSE,bracket.size = 1,size=7, label = "p.adj.signif",color="darkblue")+
  scale_y_continuous(expand=expansion(mult=c(0.05,0.1)))+theme_minimal()+
  theme(legend.position = "null",
    axis.title=element_text(colour="darkblue",        
   size=15,face = "bold"),axis.title.y=element_text(colour="darkblue"),
   axis.text.x = element_text(size=10,face = "bold"),
   axis.ticks = element_line(size = 0.1),axis.line = element_line(size=1))+
  scale_x_discrete(label=c("Ct-negative","Ct-positive"))+
  labs(y = expression(bold(Interferon-gamma~(pg/mL))),x=expression(bold(Serum~italic(Ct)~"-immoglubulin response")))


# Chlamydia Heat Shock Protein (cHSP60)

pwc_Hsp60 <- newdata %>%
  group_by(chlamydia_pos)%>%
  dunn_test(hsp_60_avrg~group,p.adjust.method = "none")
pwc_Hsp60 <- pwc_Hsp60 %>% add_xy_position(x="chlamydia_pos")

pwc_Hsp601 <- newdata %>%
  group_by(group)%>%
  dunn_test(hsp_60_avrg~chlamydia_pos,p.adjust.method = "none")
pwc_Hsp601 <- pwc_Hsp601 %>% add_xy_position(x="chlamydia_pos",group = "group")

hsp_60<-ggplot(newdata,aes(x=chlamydia_pos,y=hsp_60_avrg,col=group))+
  geom_boxplot()+scale_color_manual(name="",values = c("blue","black"))+
  geom_point(position=position_jitterdodge())+
  stat_pvalue_manual(pwc_Hsp60, tip.length = 0.02,hide.ns = FALSE,
                     y.position = c(450,450),bracket.size = 1,size=7,
                     label = "p.adj.signif",color="darkblue")+
  stat_pvalue_manual(pwc_Hsp601,y.position = c(560,515), tip.length = 0.02,
                     hide.ns = FALSE,bracket.size = 1,size=7, label = "p.adj.signif",color="darkblue")+
  scale_y_continuous(expand=expansion(mult=c(0.05,0.1)))+theme_minimal()+
  theme(legend.position = "null",
        axis.title=element_text(colour="darkblue",        
                                size=15,face = "bold"),axis.title.y=element_text(colour="darkblue"),
        axis.text.x = element_text(size=10,face = "bold"),
        axis.ticks = element_line(size = 0.1),axis.line = element_line(size=1))+
  scale_x_discrete(label=c("Ct-negative","Ct-positive"))+
  labs(y = expression(bold(italic(Ct)-heat~shock~protein~(pg/mL))),x=expression(bold(Serum~italic(Ct)~"-immoglubulin response")))

# Th1/Th2 expression Ifn-gamm/In-10
newdata<-newdata%>%mutate(ratio=ifn_gamm_avrg/il_10_avrg)
pwc_th1_2 <- newdata %>%
  group_by(chlamydia_pos)%>%
  dunn_test(ratio~group,p.adjust.method = "none")
pwc_th1_2 <- pwc_th1_2 %>% add_xy_position(x="chlamydia_pos")

pwc_th1_21 <- newdata %>%
  group_by(group)%>%
  dunn_test(ratio~chlamydia_pos,p.adjust.method = "none")
pwc_th1_21 <- pwc_th1_21 %>% add_xy_position(x="chlamydia_pos",group = "group")

Il_Ifn<-ggplot(newdata,aes(x=chlamydia_pos,y=ratio,col=group))+
  geom_boxplot()+scale_color_manual(name="",values = c("blue","black"))+
  geom_point(position=position_jitterdodge())+
  stat_pvalue_manual(pwc_th1_2, tip.length = 0.02,hide.ns = FALSE,
                     y.position = c(1.4,1.25),bracket.size = 1,size=7,
                     label = "p.adj.signif",color="darkblue")+
  stat_pvalue_manual(pwc_th1_21,y.position = c(1.7,1.5), tip.length = 0.02,
                     hide.ns = FALSE,bracket.size = 1,size=7, label = "p.adj.signif",color="darkblue")+
  scale_y_continuous(expand=expansion(mult=c(0.05,0.1)))+theme_minimal()+
  theme(legend.position = "bottom",legend.direction = "horizontal",
        axis.title=element_text(colour="darkblue",        
                                size=15,face = "bold"),axis.title.y=element_text(colour="darkblue"),
        axis.text.x = element_text(size=10,face = "bold"),
        axis.ticks = element_line(size = 0.1),axis.line = element_line(size=1))+
  scale_x_discrete(label=c("Ct-negative","Ct-positive"))+
  labs(y = expression(bold(Th1/Th2)),x=expression(bold(Serum~italic(Ct)~"-immoglubulin response")))


figure<-ggarrange(Il_10,Ifn_gam,hsp_60,Il_Ifn,labels = c("A","B","C","D")
                  ,common.legend = TRUE,legend = "bottom")
figure

```

